### ISSUE TITLE
Set Vieb as default browser on macOS

### ISSUE THREAD

**Issue by kekscode** [Jelmerro/Vieb#116]
**Addition or change**

Right now, Vieb is not added to the list of installed browsers on macOS. Clicking links do never open Vieb, but
the current default browser and there is no way to change that:

![image](https://user-images.githubusercontent.com/803252/103898052-a5de8c80-50f4-11eb-8b3b-0967cd964480.png)

**Alternatives considered**

No alternative, but multiple ways to achieve this:

On macOS the `Info.plist` file inside the application bundle `Vieb.app` is responsible for the correct configuration. This is true for any macOS application - not only for electron based apps: https://apple.stackexchange.com/questions/219582/default-browser-plist-location

I checked the electron documentation and there is a "convenience" function which could be used to achieve this. This seems to be a very concise way, because it leaves this platform-specific feature to the build environment: https://www.electronjs.org/docs/api/app#appsetasdefaultprotocolclientprotocol-path-args . I don't know about the Vieb build environment and if this can be used OOTB. Can Vieb use this electron forge or electron builder?

**Comment by Jelmerro** [comment]
This would need to be added to the electron builder config, probably with a field that I missed. Docs can be found [here](https://electron.build) if you want to check yourself. It currently only seems to work on Linux, as Windows also doesn't seem to list Vieb as a browser in the list.

**Comment by Jelmerro** [comment]
Actually, it might have something to do with the category attribute in Vieb's `electron-builder.yml` file. I'll look into this, but won't be able to test it for Mac, only for Windows (and of course Linux, but that already works).

**Comment by Jelmerro** [comment]
On Windows the file associations are working, but not the protocols. I could only find [this issue](https://github.com/electron-userland/electron-builder/issues/4582) about it, which was self-closed with a hacky workaround. So I don't think this can be solved cleanly on Windows at least.

For Mac it might be enough to add the category field I mentioned. Even if it doesn't work, it's still good to add it a category regardless, so that has been done on `master` at least. It would be great if you could try `npm run buildmac` after pulling and test if that resulting app can be set as the default browser on Mac.

**Comment by kekscode** [comment]
I tested the latest master using  `npm run buildmac` as suggested,  and i can confirm that in the resulting `Vieb.app` is an `Info.plist` file which includes settings for handling `http://` and `https://` url schemes. But it does not show up in the macOS dialog for switching the default browser, yet. I'll try to find out what's wrong here.

**Comment by kekscode** [comment]
Correction: I diffed the `Info.plist` of `3.3.0-dev` vs. `3.2.0` (after pretty printing) and the only difference which could alter behaviour is that:

        <string>public.app-category.developer-tools</string>

changed to:

        <string>public.app-category.navigation</string>

No other functional differences as far as i can see in the diff.

**Comment by Jelmerro** [comment]
I thought the category might solve the listing, as the protocol handlers are already there. So I'm not sure what is still missing for macos to detect it.

**Comment by kekscode** [comment]
Dunno. The electron-builder documentation is also weird. It states that `protocols` is inside `fileAssociations`, but the schema verification says the opposite apparently. This is my last setting after a lot of tinkering which - at least - passes validation again:

```
fileAssociations:
  name: Hypertext Markup Language
  isPackage: true
  role: None
  ext: 
    - html
    - htm
protocols:
  name: Hypertext Transfer Protocol
  schemes:
    - http
    - https
```

but this is not what the docs say and it also does not trigger an entry in the default browser dialog box. Since this is a very special usecase, i wonder if it is even supposed to work that way. Is there another electron-based browser out there which uses electron-builder to doublecheck?

**Comment by kekscode** [comment]
This is the error i get when following the docs (moving `protocols` in  `fileAssociations`):

```
> node build.js

  • electron-builder  version=22.9.1 os=20.2.0
  • loaded configuration  file=/Users/stefanantoni/devops/Vieb/electron-builder.yml
ValidationError: Invalid configuration object. electron-builder 22.9.1 has been initialized using a configuration object that does not match the API schema.
 - configuration.fileAssociations has an unknown property 'protocols'. These properties are valid:
   object { ext, description?, icon?, isPackage?, mimeType?, name?, rank?, role? }
   -> File associations.
```

**Comment by kekscode** [comment]
OK, i did the following now and have "some" success with this build config file:

```
appId: com.github.Jelmerro.vieb
linux:
  icon: app/img/icons
  executableName: vieb
  category: Network;WebBrowser;
  maintainer: Jelmer van Arnhem
  target:
    - target: AppImage
      arch:
        - x64
        - arm64
    - target: deb
      arch:
        - x64
        - arm64
    - target: freebsd
      arch:
        - x64
        - arm64
    - target: pacman
      arch:
        - x64
        - arm64
    - target: rpm
      arch:
        - x64
        - arm64
    - target: snap
      arch:
        - x64
    - target: tar.gz
      arch:
        - x64
        - arm64
  extraFiles:
    - filter:
        - README.md
        - LICENSE
rpm:
  fpm:
    - --rpm-rpmbuild-define=_build_id_links none
mac:
  category: public.app-category.navigation
  icon: app/img/icons
  target:
    - target: zip
      arch:
        - x64
win:
  icon: app/img/icons/512x512.png
  legalTrademarks: Copyright @ Jelmer van Arnhem | Licensed as free software (GPL-3.0+)
  target:
    - target: nsis
      arch:
        - x64
    - target: portable
      arch:
        - x64
    - target: zip
      arch:
        - arm64
  extraFiles:
    - filter:
        - README.md
        - LICENSE
nsis:
  oneClick: false
  license: LICENSE
fileAssociations:
  name: Hypertext Markup Language
  isPackage: true
  role: None
  ext:
    - html
    - htm
protocols:
  name: Hypertext Transfer Protocol
  schemes:
    - http
    - https
copyright: Copyright @ Jelmer van Arnhem | Licensed as free software (GPL-3.0+)
```

And additionally adding these two calls in line 422 and 423 of the `index.js` file:

```
app.setAsDefaultProtocolClient("http")
app.setAsDefaultProtocolClient("https")
```

Starting Vieb now shows this:

![image](https://user-images.githubusercontent.com/803252/104015098-74c59100-51b4-11eb-9403-040c8b00e128.png)

and clicking on `http://` and `https://` links in macOS focuses the running Vieb window.

Problems persisting:

* Vieb does not open the clicked URL yet, only its main window gets focused
*  The  `Default web browser` dialog in the General settings on macOS still does not show Vieb.app, even though i chose Vieb as my default in the dialog from the screenshot

It would be awesome if somebody on macOS with some experience with js and/or electron could help. It looks like getting this right is not as easy as setting something true/false in a build config :(
